INSERT INTO questions VALUES (16835, 'Strings', 'Concatenation', 'word = ''bungler''\nWhat is the correct output for word[2:3] * word[4:7]', 'TypeError', 'nler', 'n', 'ler' );
INSERT INTO questions VALUES (23363, 'Strings', 'Concatenation', 'word = ''starling''\nWhat is the correct output for word[0:2] * 2?', 'stst', 'stasta', 'tt', 'TypeError' );
INSERT INTO questions VALUES (95567, 'Strings', 'Concatenation', 'word = ''seminar''\nWhat is the correct output for word[1:4] * 2?', 'emiemi', 'eminemin', 'mimi', 'TypeError' );
INSERT INTO questions VALUES (21790, 'Strings', 'Concatenation', 'word = ''absolute''\nWhat is the correct output for word[2:6] * word[4:7]', 'TypeError', 'solulut', 'solu', 'lut' );
INSERT INTO questions VALUES (85304, 'Strings', 'Concatenation', 'word = ''fraction''\nWhat is the correct output for word[0:4] * 4?', 'fracfracfracfrac', 'fractfractfractfract', 'racracracrac', 'TypeError' );
INSERT INTO questions VALUES (15653, 'Strings', 'Concatenation', 'word = ''provinces''\nWhat is the correct output for word[4:7] * 2?', 'incinc', 'inceince', 'ncnc', 'TypeError' );
INSERT INTO questions VALUES (29823, 'Strings', 'Concatenation', 'word = ''anchorage''\nWhat is the correct output for word[0:4] * 3?', 'anchanchanch', 'anchoanchoancho', 'nchnchnch', 'TypeError' );
INSERT INTO questions VALUES (13999, 'Strings', 'Concatenation', 'word = ''hookers''\nWhat is the correct output for word[4:6] * 3?', 'ererer', 'ersersers', 'rrr', 'TypeError' );
INSERT INTO questions VALUES (3318, 'Strings', 'Concatenation', 'word = ''shocked''\nWhat is the correct output for word[3:5] * word[1:4]', 'TypeError', 'ckhoc', 'ck', 'hoc' );
INSERT INTO questions VALUES (19194, 'Strings', 'Concatenation', 'word = ''thistle''\nWhat is the correct output for word[2:6] * 2?', 'istlistl', 'istleistle', 'stlstl', 'TypeError' );
INSERT INTO questions VALUES (21641, 'Strings', 'Concatenation', 'word = ''abolish''\nWhat is the correct output for word[1:5] * 2?', 'boliboli', 'bolisbolis', 'olioli', 'TypeError' );
INSERT INTO questions VALUES (36342, 'Strings', 'Concatenation', 'word = ''physicals''\nWhat is the correct output for word[3:6] * 3?', 'sicsicsic', 'sicasicasica', 'icicic', 'TypeError' );
INSERT INTO questions VALUES (30413, 'Strings', 'Concatenation', 'word = ''hastens''\nWhat is the correct output for word[0:2] * 4?', 'hahahaha', 'hashashashas', 'aaaa', 'TypeError' );
INSERT INTO questions VALUES (18642, 'Strings', 'Concatenation', 'word = ''termwise''\nWhat is the correct output for word[3:7] * 4?', 'mwismwismwismwis', 'mwisemwisemwisemwise', 'wiswiswiswis', 'TypeError' );
INSERT INTO questions VALUES (75520, 'Strings', 'Concatenation', 'word = ''nurtured''\nWhat is the correct output for word[5:7] * 3?', 'rerere', 'redredred', 'eee', 'TypeError' );
INSERT INTO questions VALUES (56709, 'Strings', 'Concatenation', 'word = ''happened''\nWhat is the correct output for word[3:7] * word[4:8]', 'TypeError', 'peneened', 'pene', 'ened' );
INSERT INTO questions VALUES (52630, 'Strings', 'Concatenation', 'word = ''improved''\nWhat is the correct output for word[0:4] * 3?', 'imprimprimpr', 'improimproimpro', 'mprmprmpr', 'TypeError' );
INSERT INTO questions VALUES (50249, 'Strings', 'Concatenation', 'word = ''cleaves''\nWhat is the correct output for word[1:3] * word[4:7]', 'TypeError', 'leves', 'le', 'ves' );
INSERT INTO questions VALUES (29852, 'Strings', 'Concatenation', 'word = ''foggiest''\nWhat is the correct output for word[0:3] * word[3:5]', 'TypeError', 'foggi', 'fog', 'gi' );
INSERT INTO questions VALUES (18702, 'Strings', 'Concatenation', 'word = ''derision''\nWhat is the correct output for word[3:7] * 4?', 'isioisioisioisio', 'isionisionisionision', 'siosiosiosio', 'TypeError' );
INSERT INTO questions VALUES (61168, 'Strings', 'Concatenation', 'word = ''epiphany''\nWhat is the correct output for word[0:2] * 2?', 'epep', 'epiepi', 'pp', 'TypeError' );
INSERT INTO questions VALUES (64466, 'Strings', 'Concatenation', 'word = ''beardless''\nWhat is the correct output for word[2:4] * 4?', 'arararar', 'ardardardard', 'rrrr', 'TypeError' );
INSERT INTO questions VALUES (72435, 'Strings', 'Concatenation', 'word = ''breeches''\nWhat is the correct output for word[4:7] * 3?', 'checheche', 'cheschesches', 'hehehe', 'TypeError' );
INSERT INTO questions VALUES (70851, 'Strings', 'Concatenation', 'word = ''safeties''\nWhat is the correct output for word[2:6] * 1?', 'feti', 'fetie', 'eti', 'TypeError' );
INSERT INTO questions VALUES (23602, 'Strings', 'Concatenation', 'word = ''herewith''\nWhat is the correct output for word[2:6] * 2?', 'rewirewi', 'rewitrewit', 'ewiewi', 'TypeError' );
INSERT INTO questions VALUES (36207, 'Strings', 'Concatenation', 'word = ''merrimac''\nWhat is the correct output for word[3:7] * 4?', 'rimarimarimarima', 'rimacrimacrimacrimac', 'imaimaimaima', 'TypeError' );
INSERT INTO questions VALUES (26415, 'Strings', 'Concatenation', 'word = ''blossoms''\nWhat is the correct output for word[2:4] * word[3:6]', 'TypeError', 'ossso', 'os', 'sso' );
INSERT INTO questions VALUES (16896, 'Strings', 'Concatenation', 'word = ''disengage''\nWhat is the correct output for word[4:8] * 2?', 'ngagngag', 'ngagengage', 'gaggag', 'TypeError' );
INSERT INTO questions VALUES (88142, 'Strings', 'Concatenation', 'word = ''trudeau''\nWhat is the correct output for word[2:4] * 4?', 'udududud', 'udeudeudeude', 'dddd', 'TypeError' );
INSERT INTO questions VALUES (10183, 'Strings', 'Concatenation', 'word = ''sturgeon''\nWhat is the correct output for word[4:7] * 2?', 'geogeo', 'geongeon', 'eoeo', 'TypeError' );
INSERT INTO questions VALUES (97469, 'Strings', 'Concatenation', 'word = ''edwardian''\nWhat is the correct output for word[0:2] * 3?', 'ededed', 'edwedwedw', 'ddd', 'TypeError' );
INSERT INTO questions VALUES (31234, 'Strings', 'Concatenation', 'word = ''retrained''\nWhat is the correct output for word[0:4] * 4?', 'retrretrretrretr', 'retraretraretraretra', 'etretretretr', 'TypeError' );
INSERT INTO questions VALUES (61875, 'Strings', 'Concatenation', 'word = ''shackles''\nWhat is the correct output for word[4:5] * word[5:9]', 'TypeError', 'kles', 'k', 'les' );
INSERT INTO questions VALUES (88838, 'Strings', 'Concatenation', 'word = ''persists''\nWhat is the correct output for word[4:6] * 3?', 'isisis', 'ististist', 'sss', 'TypeError' );
INSERT INTO questions VALUES (79614, 'Strings', 'Concatenation', 'word = ''homicidal''\nWhat is the correct output for word[3:6] * 1?', 'ici', 'icid', 'ci', 'TypeError' );
INSERT INTO questions VALUES (19842, 'Strings', 'Concatenation', 'word = ''peephole''\nWhat is the correct output for word[4:7] * 2?', 'holhol', 'holehole', 'olol', 'TypeError' );
INSERT INTO questions VALUES (45299, 'Strings', 'Concatenation', 'word = ''emulators''\nWhat is the correct output for word[5:8] * 2?', 'tortor', 'torstors', 'oror', 'TypeError' );
INSERT INTO questions VALUES (88942, 'Strings', 'Concatenation', 'word = ''mumbler''\nWhat is the correct output for word[1:5] * 1?', 'umbl', 'umble', 'mbl', 'TypeError' );
INSERT INTO questions VALUES (70068, 'Strings', 'Concatenation', 'word = ''referees''\nWhat is the correct output for word[0:4] * 4?', 'referefereferefe', 'referreferreferrefer', 'efeefeefeefe', 'TypeError' );
INSERT INTO questions VALUES (29012, 'Strings', 'Concatenation', 'word = ''gaiters''\nWhat is the correct output for word[4:6] * 1?', 'er', 'ers', 'r', 'TypeError' );
INSERT INTO questions VALUES (7704, 'Strings', 'Concatenation', 'word = ''censured''\nWhat is the correct output for word[3:6] * 1?', 'sur', 'sure', 'ur', 'TypeError' );
INSERT INTO questions VALUES (13236, 'Strings', 'Concatenation', 'word = ''mcadams''\nWhat is the correct output for word[4:5] * word[1:3]', 'TypeError', 'aca', 'a', 'ca' );
INSERT INTO questions VALUES (72469, 'Strings', 'Concatenation', 'word = ''arbitrary''\nWhat is the correct output for word[2:5] * word[5:6]', 'TypeError', 'bitr', 'bit', 'r' );
INSERT INTO questions VALUES (90969, 'Strings', 'Concatenation', 'word = ''nullary''\nWhat is the correct output for word[2:5] * word[1:4]', 'TypeError', 'llaull', 'lla', 'ull' );
INSERT INTO questions VALUES (97304, 'Strings', 'Concatenation', 'word = ''oddities''\nWhat is the correct output for word[5:7] * 2?', 'ieie', 'iesies', 'ee', 'TypeError' );
INSERT INTO questions VALUES (16220, 'Strings', 'Concatenation', 'word = ''pattern''\nWhat is the correct output for word[3:6] * word[3:5]', 'TypeError', 'terte', 'ter', 'te' );
INSERT INTO questions VALUES (60099, 'Strings', 'Concatenation', 'word = ''middleton''\nWhat is the correct output for word[1:3] * 1?', 'id', 'idd', 'd', 'TypeError' );
INSERT INTO questions VALUES (85533, 'Strings', 'Concatenation', 'word = ''poisoner''\nWhat is the correct output for word[4:7] * word[2:3]', 'TypeError', 'onei', 'one', 'i' );
INSERT INTO questions VALUES (24326, 'Strings', 'Concatenation', 'word = ''blackburn''\nWhat is the correct output for word[1:5] * 1?', 'lack', 'lackb', 'ack', 'TypeError' );
INSERT INTO questions VALUES (39420, 'Strings', 'Concatenation', 'word = ''profiting''\nWhat is the correct output for word[2:6] * 3?', 'ofitofitofit', 'ofitiofitiofiti', 'fitfitfit', 'TypeError' );
INSERT INTO questions VALUES (62744, 'Strings', 'Concatenation', 'word = ''reusable''\nWhat is the correct output for word[3:7] * 1?', 'sabl', 'sable', 'abl', 'TypeError' );
INSERT INTO questions VALUES (15676, 'Strings', 'Concatenation', 'word = ''bafflers''\nWhat is the correct output for word[0:3] * 1?', 'baf', 'baff', 'af', 'TypeError' );
INSERT INTO questions VALUES (47609, 'Strings', 'Concatenation', 'word = ''installed''\nWhat is the correct output for word[6:7] * word[3:5]', 'TypeError', 'lta', 'l', 'ta' );
INSERT INTO questions VALUES (97537, 'Strings', 'Concatenation', 'word = ''eschewing''\nWhat is the correct output for word[2:4] * 3?', 'chchch', 'checheche', 'hhh', 'TypeError' );
INSERT INTO questions VALUES (65592, 'Strings', 'Concatenation', 'word = ''typeout''\nWhat is the correct output for word[3:5] * 1?', 'eo', 'eou', 'o', 'TypeError' );
INSERT INTO questions VALUES (71407, 'Strings', 'Concatenation', 'word = ''pitiful''\nWhat is the correct output for word[3:6] * 4?', 'ifuifuifuifu', 'ifulifulifuliful', 'fufufufu', 'TypeError' );
INSERT INTO questions VALUES (80628, 'Strings', 'Concatenation', 'word = ''carpets''\nWhat is the correct output for word[1:5] * word[2:4]', 'TypeError', 'arperp', 'arpe', 'rp' );
INSERT INTO questions VALUES (46575, 'Strings', 'Concatenation', 'word = ''ammonium''\nWhat is the correct output for word[3:5] * 4?', 'onononon', 'onionionioni', 'nnnn', 'TypeError' );
INSERT INTO questions VALUES (3756, 'Strings', 'Concatenation', 'word = ''casualty''\nWhat is the correct output for word[3:5] * 2?', 'uaua', 'ualual', 'aa', 'TypeError' );
INSERT INTO questions VALUES (13033, 'Strings', 'Concatenation', 'word = ''someone''\nWhat is the correct output for word[3:6] * 3?', 'eoneoneon', 'eoneeoneeone', 'ononon', 'TypeError' );
INSERT INTO questions VALUES (50660, 'Strings', 'Concatenation', 'What is the correct output for "41" * 5?', '4141414141', '205', 'TypeError', '415' );
INSERT INTO questions VALUES (62085, 'Strings', 'Concatenation', 'What is the correct output for "57" * 6?', '575757575757', '342', 'TypeError', '576' );
INSERT INTO questions VALUES (37446, 'Strings', 'Concatenation', 'What is the correct output for "51" * 6?', '515151515151', '306', 'TypeError', '516' );
INSERT INTO questions VALUES (7744, 'Strings', 'Concatenation', 'What is the correct output for "21" * 5?', '2121212121', '105', 'TypeError', '215' );
INSERT INTO questions VALUES (73909, 'Strings', 'Concatenation', 'What is the correct output for "44" * 3?', '444444', '132', 'TypeError', '443' );
INSERT INTO questions VALUES (54841, 'Strings', 'Concatenation', 'What is the correct output for "26" * 6?', '262626262626', '156', 'TypeError', '266' );
INSERT INTO questions VALUES (21228, 'Strings', 'Concatenation', 'What is the correct output for "53" * 6?', '535353535353', '318', 'TypeError', '536' );
INSERT INTO questions VALUES (11796, 'Strings', 'Concatenation', 'What is the correct output for "42" * 4?', '42424242', '168', 'TypeError', '424' );
INSERT INTO questions VALUES (63757, 'Strings', 'Concatenation', 'What is the correct output for "59" * 6?', '595959595959', '354', 'TypeError', '596' );
INSERT INTO questions VALUES (95201, 'Strings', 'Concatenation', 'What is the correct output for "31" * 4?', '31313131', '124', 'TypeError', '314' );
INSERT INTO questions VALUES (48308, 'Strings', 'Concatenation', 'What is the correct output for "22" * 6?', '222222222222', '132', 'TypeError', '226' );
INSERT INTO questions VALUES (91235, 'Strings', 'Concatenation', 'What is the correct output for "11" * 6?', '111111111111', '66', 'TypeError', '116' );
INSERT INTO questions VALUES (79035, 'Strings', 'Concatenation', 'What is the correct output for "11" * 6?', '111111111111', '66', 'TypeError', '116' );
INSERT INTO questions VALUES (82989, 'Strings', 'Concatenation', 'What is the correct output for "58" * 6?', '585858585858', '348', 'TypeError', '586' );
INSERT INTO questions VALUES (38517, 'Strings', 'Concatenation', 'What is the correct output for "27" * 6?', '272727272727', '162', 'TypeError', '276' );
INSERT INTO questions VALUES (82233, 'Strings', 'Concatenation', 'What is the correct output for "28" * 5?', '2828282828', '140', 'TypeError', '285' );
INSERT INTO questions VALUES (64414, 'Strings', 'Concatenation', 'What is the correct output for "39" * 6?', '393939393939', '234', 'TypeError', '396' );
INSERT INTO questions VALUES (20609, 'Strings', 'Concatenation', 'What is the correct output for "15" * 5?', '1515151515', '75', 'TypeError', '155' );
INSERT INTO questions VALUES (64119, 'Strings', 'Concatenation', 'What is the correct output for "51" * 3?', '515151', '153', 'TypeError', '513' );
INSERT INTO questions VALUES (49481, 'Strings', 'Concatenation', 'What is the correct output for "45" * 3?', '454545', '135', 'TypeError', '453' );
INSERT INTO questions VALUES (51731, 'Strings', 'Concatenation', 'What is the correct output for "11" * 4?', '11111111', '44', 'TypeError', '114' );
INSERT INTO questions VALUES (55379, 'Strings', 'Concatenation', 'What is the correct output for "50" * 5?', '5050505050', '250', 'TypeError', '505' );
INSERT INTO questions VALUES (10687, 'Strings', 'Concatenation', 'What is the correct output for "12" * 6?', '121212121212', '72', 'TypeError', '126' );
INSERT INTO questions VALUES (85026, 'Strings', 'Concatenation', 'What is the correct output for "34" * 6?', '343434343434', '204', 'TypeError', '346' );
INSERT INTO questions VALUES (91416, 'Strings', 'Concatenation', 'What is the correct output for "42" * 3?', '424242', '126', 'TypeError', '423' );
INSERT INTO questions VALUES (2913, 'Strings', 'Concatenation', 'What is the correct output for "28" * 5?', '2828282828', '140', 'TypeError', '285' );
INSERT INTO questions VALUES (24009, 'Strings', 'Concatenation', 'What is the correct output for "12" * 3?', '121212', '36', 'TypeError', '123' );
INSERT INTO questions VALUES (99805, 'Strings', 'Concatenation', 'What is the correct output for "50" * 5?', '5050505050', '250', 'TypeError', '505' );
INSERT INTO questions VALUES (1974, 'Strings', 'Concatenation', 'What is the correct output for "51" * 6?', '515151515151', '306', 'TypeError', '516' );
INSERT INTO questions VALUES (50630, 'Strings', 'Concatenation', 'What is the correct output for "26" * 6?', '262626262626', '156', 'TypeError', '266' );